apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: my-container
    image: public.ecr.aws/docker/library/alpin
    command: ["sleep"]
    args:
    - 10h
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: my-container
    image: public.ecr.aws/docker/library/alpine
    command: ["sleep"]
    args:
    - 10h
